### ISSUE TITLE
Failed to acquire lock after 00:01:00. Timeout

### ISSUE THREAD

**Issue by peda** [fiskaltrust/product-de-bring-your-own-datacenter#31]
**Describe the bug**
We upgraded BYODC from 1.3.11 to 1.3.12 yesterday (3rd February 2021)
With 1.3.11 we did not have a single locking issue
Since upgrading 1.3.12 we do have locking issues every 5 to 10 requests - it usually takes around 5-10 minutes for it to resolve by itself

We are using a Fiskaly TSE (not sure if it is related

**To Reproduce**
unknown - behavior seems random - happens on regular receipt signing requests

it does not seem to be related to the request itself, because when we retry the same request over and over again (2-3 minutes) it does work after a few retries

The **request immediately before the locking issue** does occur does always return the following plain text response:
 ```
upstream connect error or disconnect/reset before headers. reset reason: connection termination
 ```

**Expected behavior**
there shouldn't be any locking issues - this is usually an indicator that something crashed

**Screenshots**
not applicable

**Log file from all BYODC pods**

Log file timestamps are in CET (UTC+1) - this is important when comparing it with the request timestamps listed in the additional context.

```
2021-02-04 10:14:13.424 byodc-6d49d56b95-mg47m byodc info info: fiskaltrust.SignatureCloud.DE.Services.MiddlewareInstanceFactory[0]
      Worker created. cashboxid: 98d8c0dc-1ffb-4066-9cf9-60d0a8642340
2021-02-04 10:15:38.351 byodc-6d49d56b95-mg47m byodc info info: fiskaltrust.SignatureCloud.DE.Startup[0]
      Redis is configured.
2021-02-04 10:15:48.353 byodc-6d49d56b95-mg47m byodc info info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
2021-02-04 10:15:48.353 byodc-6d49d56b95-mg47m byodc info info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
2021-02-04 10:15:48.353 byodc-6d49d56b95-mg47m byodc info info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
2021-02-04 10:15:48.353 byodc-6d49d56b95-mg47m byodc info info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
2021-02-04 10:16:32.051 byodc-6d49d56b95-mg47m byodc warn warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
2021-02-04 10:16:40.967 byodc-6d49d56b95-6sxvt byodc warn warn: fiskaltrust.SignatureCloud.DE.Services.HelipadUploader[0]
      Failed to remove queue upload for cashbox cashbox. cashboxid: 98d8c0dc-1ffb-4066-9cf9-60d0a8642340
2021-02-04 10:16:40.970 byodc-6d49d56b95-7khcj byodc warn warn: fiskaltrust.SignatureCloud.DE.Services.HelipadUploader[0]
      Failed to remove queue upload for cashbox cashbox. cashboxid: 98d8c0dc-1ffb-4066-9cf9-60d0a8642340
2021-02-04 10:17:03.057 byodc-6d49d56b95-mg47m byodc info info: fiskaltrust.SignatureCloud.DE.Services.MiddlewareInstanceFactory[0]
      Worker created. cashboxid: 98d8c0dc-1ffb-4066-9cf9-60d0a8642340
2021-02-04 10:18:04.257 byodc-6d49d56b95-mg47m byodc fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM68TM7LDNEC", Request id "0HM68TM7LDNEC:00000002": An unhandled exception was thrown by the application.
      System.TimeoutException: Failed to acquire lock after 00:01:00. Timeout
         at fiskaltrust.SignatureCloud.DE.Services.Locking.RedisLockService.ProcessLockiningAsync[T](String lockName, Func`1 executeMethod) in /src/src/fiskaltrust.SignatureCloud.DE/Services/Locking/RedisLockService.cs:line 33
         at fiskaltrust.SignatureCloud.DE.Controllers.SignController.Post(ReceiptRequest request) in /src/src/fiskaltrust.SignatureCloud.DE/Controllers/SignController.cs:line 96
         at lambda_method4(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**POSSystem (please complete the following information):**
- `ecda5b15-104f-4f37-b7d1-d42babda1b4b`

**Cashbox Information (please complete the following information):**
 - `98d8c0dc-1ffb-4066-9cf9-60d0a8642340`

**Additional context**
Timestamp of request which caused the `upstream connect error or disconnect/reset before headers. reset reason: connection termination` error: `2021-02-04T09:14:30.395Z`

Before this one I had only one other receipt signed (was the first receipt today) at (`Moment`) `2021-02-04T09:14:07.139Z` - the `ftReceiptMoment` for this receipt was `2021-02-04T09:14:13.907224Z`

4th retry was successful at `2021-02-04T09:20:35.256Z`

**Comment by fiskaltrust-ckr** [comment]
Hi @peda
thank you for this question.

Could you try to downgrade the BackendPOD by adding the following to the config.yaml, please?

```
byodc:
  image:
    tag: 1.3.11-rc1-buster
```

Do you use our predefined Redis POD or do you connect to a Redis Instance of yours?

BR
Christian

**Comment by mertcanyalhi** [comment]
@peda can you check if the worker pod had restarted? for our case, we are having the same error after the worker pod restarted due to `OOMKilled`.

**Comment by peda** [comment]
@fiskaltrust-ckr sorry, just saw your reply today - must have missed the notification in my emails

I will try the version `1.3.11-rc1-buster` tomorrow

We are using the predefined Redis POD

@mertcanyalhi we are already running 256Mi memory - with the default value of 100Mi it crashed at 30% of all requests
maybe I'm just looking in the wrong place, but I couldn't find any `OOMKilled` message in our log files

**Comment by mertcanyalhi** [comment]
@peda I think 256Mi is a bit low. in our case, a pod consumes ~360 MB when it is idle (after a worker is created) and ~450 MB max when you create a report. you also need to increase the CPU resource (for us, 500m worked) since we had `lock acquire timeout` during load tests with the default setting.

based on your feedback, I think the memory consumption might have increased with the version you're using, but I'm just guessing.

you can check the restart count via `kubectl get pods` and check the previous restart reason with `kubectl get pod <POD_NAME> --output=yaml` which will be under `containerStatuses`.

**Comment by peda** [comment]
@mertcanyalhi thanks for your feedback - looks like it is indeed memory realted
```
lastState:
      terminated:
        containerID: docker://ba72890b5325d894863b470eab4a60eea91e5f4c0304560f7e1ca2a4b5d2a2b2
        exitCode: 137
        finishedAt: "2021-02-24T19:23:14Z"
        reason: OOMKilled
        startedAt: "2021-02-17T21:39:46Z"
```

**Comment by peda** [comment]
@mertcanyalhi I've increased memory to 512Mi und CPU to 500m and so the issue did not happen again - will do some test with higher load tomorrow

**Comment by mertcanyalhi** [comment]
@peda happy to hear that!
