### ISSUE TITLE
redis port and channel settings NOT working

### ISSUE THREAD

**Issue by peda** [fiskaltrust/product-de-bring-your-own-datacenter#38]
**Describe the bug**
If the redis port is changed `byodc` fails to start with an exception

If the redis channel is changed and both the sandbox and the live environment are running on the same kubernetes cluster (even though in different namespaces) then some messages end up in the wrong environment and the web service does return `configuration not readable`

```
byodc:
...
  config:
    redis:
      # hostname of the redis instance (only change if using external redis instance)
      host: redis
      # port of the redis instance (also sets the port for the internal redis instance)
      port: 6375
      channel: byodc-stg
...
```

**Log when changing redis channel**
```
fiskaltrust.SignatureCloud.DE.Services.MiddlewareInstanceFactory[0]
      Failed to get configuration. cashboxid: 91df5c17-0cdc-4f25-9d9b-4bc4b10ce662, download: False
      fiskaltrust.SignatureCloud.DE.Services.HelipadException: Unauthorized
         at fiskaltrust.SignatureCloud.DE.Services.HelipadService.GetConfigurationAsync(Guid cashBoxId, String accessToken) in /src/src/fiskaltrust.SignatureCloud.DE/Services/HelipadService.cs:line 182
         at fiskaltrust.SignatureCloud.DE.Services.MiddlewareInstanceFactory.GetConfiguration(Guid cashboxid, String accesstoken, Boolean download) in /src/src/fiskaltrust.SignatureCloud.DE/Services/MiddlewareInstanceFactory.cs:line 71
```

**Log when changing redis port**
```
Unhandled exception. StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on redis:6375/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.2.4.27433
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1163
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1032
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1015
   at fiskaltrust.SignatureCloud.DE.Startup.<>c__DisplayClass5_0.<RegisterRedisServices>b__0(IServiceProvider x) in /src/src/fiskaltrust.SignatureCloud.DE/Startup.cs:line 112
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at fiskaltrust.SignatureCloud.DE.Program.Main(String[] args) in /src/src/fiskaltrust.SignatureCloud.DE/Program.cs:line 16
```

**Comment by peda** [comment]
It looks like the root cause of this issue was ambassador which was looking in other namespaces as well for services of the same type adding the following to the config.yaml seems to resolve this issue

```
redis:
 ...
  scope:
    singleNamespace: true
```

I will do some further validation tomorrow, but nevertheless changing the redis port is not working.

**Comment by volllly** [comment]
Please try setting the redis host to the following:
```yaml
byodc:
...
  config:
    redis:
      host: redis.<namespace>
```
(using your namespace for `<namespace>`)
This should fix the issues with different namespaces.

We will add this and a fix for setting the redis port to the next release.

**Comment by peda** [comment]
@volllly 
thanks that worked - but only when also adding scope.singleNamespace to `ambassador` - otherwise ambassador seems to distribute the incoming requests to all `byodc` - even in other namespaces

**Comment by volllly** [comment]
We've released version `1.3.17` of the helm chart which fixes the redis port changing issue and added the necessary configuration to run multiple deployments on one cluster.

you should be able to remove the `ambassador.scope.singleNamespace` and `byodc.config.redis.host` settings from your `config.yaml`.

Please let us know if you encounter any further problems.

**Comment by peda** [comment]
thanks - I'll give it a try later today

**Comment by peda** [comment]
@volllly thanks again - I can confirm that this is working now in version `1.3.17`
